"""
Sherlock job script to execute MIDAS snps processing
"""
#!/bin/bash
#SBATCH --nodes=2
#SBATCH --mem=10G
#SBATCH --job-name=midas_fastqs_snps
#SBATCH --error=whole_midas_snps_%j.err
#SBATCH --output=whole_midas_snps_%j.out
#SBATCH --time=5-00:00:00

ml py-numpy/1.14.3_py27
ml py-pandas/0.23.0_py27
ml biology
ml py-biopython/1.70_py27
ml py-pysam/0.14.1_py27
ml bowtie2

python $HOME/run_midas_fastqs.py $SCRATCH/SraRunTable_Relevant.tsv $HOME/snps.sh
sbatch -c 4 run_midas_fastqs_snps.job